id: PE99138DF
initial_creation_type: input
source_metadata:
  title: Chomden Rigpé Raldri
  language: bo
  description: 'Texts by and about Chomden Rigpé Raldri (bcom ldan rig pa''i ral gri,
    1227–1305), a celebrated scholar connected with Narthang Monastery:'
  volume:
    60b39d07ceef4deea92f1baf2b338a24:
      title: Synopsis of the Treasury of Abhidharma (Abhidharmakośa)
      parent: Abhidharma
created_at: '2022-02-28T22:48:44.149494'
last_modified_at: '2022-02-28T22:48:44.149497'
statistics:
  total_words: 1207
  total_non_words: 167
quality:
  non_words_ratio: 0.14
